### ISSUE TITLE
Version 1.1.1 breaks with "RuboCop::ValidationError: unrecognized cop or department inherit_from" when targeting legacy rubies

### ISSUE THREAD

**Issue by ivoanjo** [standardrb/standard-performance#11]
Hey here :wave:

As usual, thanks a lot for standard! We're using it at Datadog on the [`libdatadog`](https://github.com/DataDog/libdatadog/tree/main/ruby) gem.

I just noticed that our CI picked up standard-performance 1.1.1 and it started failing:

```
$ bundle exec  rake standard
rake aborted!
RuboCop::ValidationError: unrecognized cop or department inherit_from found in .rvm/gems/ruby-3.2.2/gems/standard-performance-1.1.1/lib/standard/performance/plugin.rb
.rvm/gems/ruby-3.2.2/gems/rubocop-1.52.1/lib/rubocop/config_validator.rb:117:in `alert_about_unrecognized_cops'
.rvm/gems/ruby-3.2.2/gems/rubocop-1.52.1/lib/rubocop/config_validator.rb:46:in `validate'
.rvm/gems/ruby-3.2.2/gems/rubocop-1.52.1/lib/rubocop/config.rb:55:in `check'
.rvm/gems/ruby-3.2.2/gems/rubocop-1.52.1/lib/rubocop/config.rb:26:in `create'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/plugin/merges_plugins_into_rubocop_config.rb:63:in `config_for_plugin'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/plugin/merges_plugins_into_rubocop_config.rb:42:in `block (2 levels) in combine_rubocop_configs'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/plugin/merges_plugins_into_rubocop_config.rb:40:in `each'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/plugin/merges_plugins_into_rubocop_config.rb:40:in `reduce'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/plugin/merges_plugins_into_rubocop_config.rb:40:in `block in combine_rubocop_configs'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/plugin/merges_plugins_into_rubocop_config.rb:137:in `fake_out_rubocop_default_configuration'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/plugin/merges_plugins_into_rubocop_config.rb:39:in `combine_rubocop_configs'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/plugin/merges_plugins_into_rubocop_config.rb:30:in `call'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/plugin/combines_plugin_configs.rb:11:in `call'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/creates_config_store.rb:22:in `block in call'
<internal:kernel>:90:in `tap'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/creates_config_store.rb:19:in `call'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/builds_config.rb:26:in `call'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/cli.rb:13:in `run'
.rvm/gems/ruby-3.2.2/gems/standard-1.30.1/lib/standard/rake.rb:17:in `block in <top (required)>'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in `load'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:58:in `kernel_load'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/cli/exec.rb:23:in `run'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/cli.rb:492:in `exec'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/cli.rb:34:in `dispatch'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/cli.rb:28:in `start'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/exe/bundle:37:in `block in <top (required)>'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
.rvm/gems/ruby-3.2.2/gems/bundler-2.4.14/exe/bundle:29:in `<top (required)>'
.rvm/gems/ruby-3.2.2/bin/bundle:25:in `load'
.rvm/gems/ruby-3.2.2/bin/bundle:25:in `<main>'
```

Reverting back to 1.1.0 makes the issue go away.

This seems to be triggered by our use of `ruby_version: 2.1` (or 2.2) in `.standard.yml`. Changing it to a later version (e.g 2.3+) also makes the issue go away.

I know that keeping these things working on these really old Ruby versions is annoying (sigh..), and we can pin standard-performance if needed, but I thought I'd report it anyway :)

**Comment by searls** [comment]
Thanks, this behavior is definitely a bug. Any steps in particular to reproduce this in that repo?

**Comment by searls** [comment]
This is fixed in v1.1.2 -- thanks for the report, pretty significant oversight on my part.

**Comment by ivoanjo** [comment]
Thanks a lot for the quick fix and still bothering with us folks still running on 2.1/2.2

**Comment by ivoanjo** [comment]
Thanks a lot for the quick fix and still bothering with us folks still running on 2.1/2.2
